### ISSUE TITLE
Remove empty tooltip bubble if document has no description

### ISSUE THREAD

**Issue by mikestp27** [smoreau/redmine_documents_short#4]
Thank you for you plugin.  It's great.  It's probably how Redmine should display documents in the first place...

I have some document without description.  Probably not ideal but it's a step better than having them in multiple folders on people's computers...

We like the tooltip bubbles but it shows empty bubbles when the documents have no description.   

We don't have much experience in Ruby/Rails so making a fix there was a stretch... but we managed to do something in javascript.  So we modified app/views/documents/index.html.erb and added some javascript just before the call to Opentip...

```
<script type="text/javascript">
// remove tooltip bubble if document has no description
$("a").each( function(){
        if($.trim($(this).attr("data-ot"))==="") {
                $(this).removeAttr("data-ot");
        };
});
// Create a style for all document Opentips
Opentip.styles.document = {
        extends: "dark",
        target: true,
        tipJoint: "top"
};

// Now set the style as default
Opentip.defaultStyle = "document";
</script>
```

**Comment by smoreau** [comment]
Thanks mikestp27 for opening this issue.
I fixed it but I did it directly in the Rails code to avoid impacting the client browser with Javascript.
