### ISSUE TITLE
Git clone command line outdated

### ISSUE THREAD

**Issue by ffdarkpenguin** [smoreau/redmine_documents_short#6]
Hi @smoreau,

  I was testing your redmine plugin and got stuck with and old github sintaxe that took me a while to notice. 

  I've tried to open a PR with the fix but your repo wont allow it.

  Please see if you can fix it. 

  Github no longer allows:
    `git clone git://github.com/smoreau/redmine_documents_short.git`

  You must use ssh or other supported path to download it. In my PR I would just replace the line above with:

  `git clone git@github.com:smoreau/redmine_documents_short.git`

  which uses ssh and works.

  Also, if the documentation on redmine plugins directory is not the same consider fixing there too, please.

  Thanks.

Flávio

**Comment by smoreau** [comment]
Thank you for your message.
I fixed the documentation as per your remarks. :)
